// <auto-generated />
using System;
using System.Collections.Generic;
using Inventory_Management_Platform.Data;
using Inventory_Management_Platform.Models.CustomId;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Inventory_Management_Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307003614_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventory_Management_Platform.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Office Equipment"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Name = "HR Documents"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Software Licenses"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bool1Description")
                        .HasColumnType("text");

                    b.Property<bool>("Bool1Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Bool1Name")
                        .HasColumnType("text");

                    b.Property<int>("Bool1OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("Bool1ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("Bool2Description")
                        .HasColumnType("text");

                    b.Property<bool>("Bool2Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Bool2Name")
                        .HasColumnType("text");

                    b.Property<int>("Bool2OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("Bool2ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("Bool3Description")
                        .HasColumnType("text");

                    b.Property<bool>("Bool3Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Bool3Name")
                        .HasColumnType("text");

                    b.Property<int>("Bool3OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("Bool3ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<CustomIdElement>>("CustomIdFormat")
                        .HasColumnType("jsonb");

                    b.Property<string>("DescriptionMd")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Link1Description")
                        .HasColumnType("text");

                    b.Property<bool>("Link1Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Link1Name")
                        .HasColumnType("text");

                    b.Property<int>("Link1OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("Link1ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("Link2Description")
                        .HasColumnType("text");

                    b.Property<bool>("Link2Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Link2Name")
                        .HasColumnType("text");

                    b.Property<int>("Link2OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("Link2ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("Link3Description")
                        .HasColumnType("text");

                    b.Property<bool>("Link3Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Link3Name")
                        .HasColumnType("text");

                    b.Property<int>("Link3OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("Link3ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("MultiLine1Description")
                        .HasColumnType("text");

                    b.Property<bool>("MultiLine1Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MultiLine1Name")
                        .HasColumnType("text");

                    b.Property<int>("MultiLine1OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("MultiLine1ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("MultiLine2Description")
                        .HasColumnType("text");

                    b.Property<bool>("MultiLine2Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MultiLine2Name")
                        .HasColumnType("text");

                    b.Property<int>("MultiLine2OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("MultiLine2ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("MultiLine3Description")
                        .HasColumnType("text");

                    b.Property<bool>("MultiLine3Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MultiLine3Name")
                        .HasColumnType("text");

                    b.Property<int>("MultiLine3OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("MultiLine3ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("Numeric1Description")
                        .HasColumnType("text");

                    b.Property<bool>("Numeric1Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Numeric1Name")
                        .HasColumnType("text");

                    b.Property<int>("Numeric1OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("Numeric1ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("Numeric2Description")
                        .HasColumnType("text");

                    b.Property<bool>("Numeric2Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Numeric2Name")
                        .HasColumnType("text");

                    b.Property<int>("Numeric2OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("Numeric2ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("Numeric3Description")
                        .HasColumnType("text");

                    b.Property<bool>("Numeric3Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Numeric3Name")
                        .HasColumnType("text");

                    b.Property<int>("Numeric3OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("Numeric3ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Title", "DescriptionMd" });

                    b.Property<string>("String1Description")
                        .HasColumnType("text");

                    b.Property<bool>("String1Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("String1Name")
                        .HasColumnType("text");

                    b.Property<int>("String1OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("String1ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("String2Description")
                        .HasColumnType("text");

                    b.Property<bool>("String2Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("String2Name")
                        .HasColumnType("text");

                    b.Property<int>("String2OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("String2ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("String3Description")
                        .HasColumnType("text");

                    b.Property<bool>("String3Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("String3Name")
                        .HasColumnType("text");

                    b.Property<int>("String3OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("String3ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.InventoryAccess", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("InventoryId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryAccesses");
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.InventoryTag", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("InventoryId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("InventoryTags");
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("Bool1Value")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Bool2Value")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Bool3Value")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Link1Value")
                        .HasColumnType("text");

                    b.Property<string>("Link2Value")
                        .HasColumnType("text");

                    b.Property<string>("Link3Value")
                        .HasColumnType("text");

                    b.Property<string>("MultiLine1Value")
                        .HasColumnType("text");

                    b.Property<string>("MultiLine2Value")
                        .HasColumnType("text");

                    b.Property<string>("MultiLine3Value")
                        .HasColumnType("text");

                    b.Property<decimal?>("Numeric1Value")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Numeric2Value")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Numeric3Value")
                        .HasColumnType("numeric");

                    b.Property<string>("String1Value")
                        .HasColumnType("text");

                    b.Property<string>("String2Value")
                        .HasColumnType("text");

                    b.Property<string>("String3Value")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("InventoryId", "CustomId")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.Like", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("ItemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentMd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("InventoryId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.Inventory", b =>
                {
                    b.HasOne("Inventory_Management_Platform.Models.Category", "Category")
                        .WithMany("Inventories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Inventory_Management_Platform.Models.AppUser", "Owner")
                        .WithMany("OwnedInventories")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.InventoryAccess", b =>
                {
                    b.HasOne("Inventory_Management_Platform.Models.Inventory", "Inventory")
                        .WithMany("AccessList")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Management_Platform.Models.AppUser", "User")
                        .WithMany("InventoryAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.InventoryTag", b =>
                {
                    b.HasOne("Inventory_Management_Platform.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Management_Platform.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.Item", b =>
                {
                    b.HasOne("Inventory_Management_Platform.Models.AppUser", "CreatedBy")
                        .WithMany("CreatedItems")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Inventory_Management_Platform.Models.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.Like", b =>
                {
                    b.HasOne("Inventory_Management_Platform.Models.Item", "Item")
                        .WithMany("Likes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Management_Platform.Models.AppUser", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.Post", b =>
                {
                    b.HasOne("Inventory_Management_Platform.Models.AppUser", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Management_Platform.Models.Inventory", "Inventory")
                        .WithMany("Posts")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Inventory_Management_Platform.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Inventory_Management_Platform.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Management_Platform.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Inventory_Management_Platform.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.AppUser", b =>
                {
                    b.Navigation("CreatedItems");

                    b.Navigation("InventoryAccesses");

                    b.Navigation("Likes");

                    b.Navigation("OwnedInventories");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.Category", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.Inventory", b =>
                {
                    b.Navigation("AccessList");

                    b.Navigation("Items");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Inventory_Management_Platform.Models.Item", b =>
                {
                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
